AWSTemplateFormatVersion: "2010-09-09"
Description: IAM CloudFormation Template
Resources:
  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: jxsCFN
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  # My IAM Group
  MyIAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: jxsCFNGroup

  # Attach the user to the group
  UserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref MyIAMGroup
      Users:
        - !Ref MyIAMUser

  # IAM Role for EC2
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
  # S3 Custom Policy
  MyS3CustomPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3CustomPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
            Resource:
              - arn:aws:s3:::my-bucket-name
              - arn:aws:s3:::my-bucket-name/*
      Roles:
        - !Ref MyIAMRole
