# CloudFormationTemplateVersion
# Description: CloudFormation

AWSTemplateFormatVersion: "2010-09-09"
Description: "Cloudformation template for S3 Bucket"
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "jxs-s3-bucket01-yaml"
`